name: AutoSignIn

on:
  push:

jobs:
  AutoSignIn:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: 'Set up Python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: 'Install requirements'
      run: |
        pip install -r requirements.txt
 
    - name: Run
      run: |
        python3 dome.py
