name: AutoSignIn

on:
  push:
  gollum:
  schedule:
    - cron: 0 2 * * *

jobs:
  AutoSignIn:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v1
    - name: 'Set up Python'
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
    - name: 'Install requirements'
      run: |
        pip3 install -r requirements.txt
 
    - name: Run
      run: |
        python3 main.py
